### PR TITLE
upgrade argonaut to 6.3.0-M2

### PR DESCRIPTION
**Pull request by alissapajer**

### CODE REVIEW

**Comment by rintcius** [comment]
@alissapajer Another PR that has slipped through. It's approved but has a conflict now

**Comment by alissapajer** [comment]
thanks @rintcius! just pushed up a fix to resolve the conflict

**Comment by alissapajer** [comment]
hm
```
sbt.librarymanagement.ResolveException: Error downloading io.argonaut:argonaut_2.11:6.3.0-M2
```

**Comment by wemrysi** [comment]
Superseded by #76

**Pull request closed without merging**
